### ISSUE TITLE
Scheduled job patch doesn't fit latest versions of CiviCRM

### ISSUE THREAD

**Issue by dandoran-wp** [PalanteJon/coop.palantetech.countylookup#2]
Since about CiviCRM 4.7.10(?), the BatchUpdate.php script has been extensively refactored, and the patch  you helpfully provided in your README ("It does NOT work with the geocoding scheduled job without the following change to CiviCRM core: ...") no longer applies.

**Comment by MegaphoneJon** [comment]
Thank you for the feedback - you're right!  And I should know, I was the one who [did the refactor](https://github.com/civicrm/civicrm-core/commit/f78a9f72a9f204c8249b046bf2db09ac36d794bb#diff-02fa61be3ddb7f21ceb91f15373fdcd0).

The day I did this, I was with the fine folks at Ginkgo Street Labs, who convinced me that their [GeoFill extension](https://github.com/ginkgostreet/com.ginkgostreet.geofill) does everything this extension does and more, so I haven't paid much attention.  But I'll update the README for sure.

Thanks,
Jon
