### ISSUE TITLE
Some addresses in Westmoreland County, Pennsylvania registering in other counties.

### ISSUE THREAD

**Issue by pmosey** [PalanteJon/coop.palantetech.countylookup#4]
Most of the addresses in Westmoreland County, PA are correctly applied to Westmoreland. However, some are placed in the wrong county.
For instance, if I look up all of our contacts in Mount Pleasant, PA (29 total) 6 of them are assigned Fayette County instead of Westmoreland.
I've checked each of these addresses against online databases and they all come up in Westmoreland.
Mount Pleasant is just one example. There are other towns that are in Westmoreland County that are assigned to different counties in Civi.
An example address is 265 E Main St Mount Pleasant, PA 15666 
Coordinates automatically applied in Civi: 40.1468238,-79.527278
Civi shows it as Fayette not Westmoreland.
Scottdale, PA: 23 total contacts, 5 addresses are tied to Fayette instead of Westmoreland.
Vandergrift, PA:  7 contacts, 3 addresses are marked as Armstrong County instead of Westmoreland.
Seward, PA: 7 contacts, 2 addresses are marked as Indiana County instead of Westmoreland.

**Comment by MegaphoneJon** [comment]
Sorry - I don't have a Google API key to test this with.

**Comment by MegaphoneJon** [comment]
This data is coming from your provider, presumably Google (I don't think I ever added support for others).  If the data is no good, you can try [fixing it with Google](https://support.google.com/maps/answer/3094088?hl=en).

I believe the Geocoder extension can be configured to do county lookups with most of its providers (no GUI for editing the config though).  So you can try another provider to see if that helps.
