### ISSUE TITLE
County Lookup v1.2 gives critical error when trying to use Smarty v5

### ISSUE THREAD

**Issue by mikesafh** [PalanteJon/coop.palantetech.countylookup#6]
Like several other extensions, this one probably needs to be run through civix again. I could, but there are lots of unknowns about how to answer all the questions that process asks you.

Enabling County Lookup throws a fatal error, partial stacktrace:

[27-Oct-2024 10:48:40 America/New_York] PHP Fatal error:  Uncaught Error: Cannot access protected property Smarty\Smarty::$template_dir in /var/www/html/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php:37
Stack trace:
#0 /var/www/html/wp-content/uploads/civicrm/ext/countylookup-master/countylookup.civix.php(99): Smarty->__get()
#1 /var/www/html/wp-content/uploads/civicrm/ext/countylookup-master/countylookup.civix.php(167): _countylookup_civix_civicrm_config()
#2 /var/www/html/wp-content/uploads/civicrm/ext/countylookup-master/countylookup.php(128): _countylookup_civix_civicrm_enable()

Any chance for an update to this extension? The ginkostreet one throws the same error and that's no longer being supported.

Thank you.

Michael

**Comment by MegaphoneJon** [comment]
Hi @mikesafh - I can't find a version of this extension (in the last few) that has a call to Smarty on line 99 of `countylookup.civix.php`.  And I already pushed civix 23.02.1, which I thought should cover Smarty 5 issues -  but I just pushed 24.09.1.  Please confirm it resolves your issue?

**Comment by mikesafh** [comment]
Jon,Thanks for looking into it. After getting some feedback on the CiviCRM StackExchange site, I ran civix upgrade on the plugin over the weekend which seems to have resolved all my issues and is probably the same thing you did.I think also that the download page on this page: https://civicrm.org/extensions/county-lookup is still pointing to an old version. Points to the correct and updated GitHub URL, but not sure how that would get updated.Thanks.MichaelOn Oct 28, 2024, at 01:12, Jon ***@***.***> wrote:﻿
Hi @mikesafh - I can't find a version of this extension (in the last few) that has a call to Smarty on line 99 of countylookup.civix.php.  And I already pushed civix 23.02.1, which I thought should cover Smarty 5 issues -  but I just pushed 24.09.1.  Please confirm it resolves your issue?

**Comment by MegaphoneJon** [comment]
Thanks Michael.  I don't use this extension anymore but I'll make a new version.
